import { toNumber } from "@/lib/gold";

export type GoalTrade = { id?: number; tradeDate: Date | string | number; pnl: number | string | null; result: string; risk?: number | string | null; reward?: number | string | null; patienceScore?: number | null; setupQuality?: string | null; hasScreenshot?: boolean; mistake?: string | null };
export type GoalPlan = { planDate: Date | string | number; overallRating?: number | null };
export type TraderGoal = { id: number; name: string; description?: string | null; period: "DAILY" | "WEEKLY" | "MONTHLY"; metric: string; comparison: "GTE" | "LTE"; target: string | number; active: boolean; notify?: boolean; isCustom?: boolean };
export type TraderGoalStatus = "PENDING" | "IN_PROGRESS" | "MET" | "SAFE" | "AT_RISK" | "BREACHED";

const keyFormatter = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" });
function dayKey(value: Date | string | number) { const parts = keyFormatter.formatToParts(new Date(value)); const get = (type: string) => parts.find(part => part.type === type)?.value ?? "00"; return `${get("year")}-${get("month")}-${get("day")}`; }
function calendarDate(key: string) { const [year, month, day] = key.split("-").map(Number); return new Date(Date.UTC(year, month - 1, day)); }
function shiftKey(key: string, days: number) { const date = calendarDate(key); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function periodStart(period: TraderGoal["period"], now: Date) { const today = dayKey(now); if (period === "DAILY") return today; if (period === "MONTHLY") return `${today.slice(0, 8)}01`; const date = calendarDate(today); const offset = (date.getUTCDay() + 6) % 7; return shiftKey(today, -offset); }
function maxDrawdown(rows: GoalTrade[]) { let equity = 0; let peak = 0; let worst = 0; for (const row of rows) { equity += toNumber(row.pnl); peak = Math.max(peak, equity); worst = Math.max(worst, peak - equity); } return worst; }
function currentLossStreak(rows: GoalTrade[]) { let streak = 0; for (const row of [...rows].reverse()) { if (row.result !== "LOSS") break; streak += 1; } return streak; }

export function goalCategory(metric: string) { return ["daily_loss", "weekly_drawdown", "trade_count", "consecutive_losses"].includes(metric) ? "RISK GUARDRAIL" : ["revenge_trades", "avg_patience", "quality_setup", "screenshot_rate", "weekly_reviews"].includes(metric) ? "PROCESS DISCIPLINE" : "PERFORMANCE"; }
export function goalMetricLabel(metric: string) { return ({ trade_count: "Trades", daily_loss: "Daily loss", revenge_trades: "Revenge tags", avg_patience: "Patience average", win_rate: "Win rate", avg_rr: "Average R:R", weekly_drawdown: "Drawdown", quality_setup: "A / A+ setup rate", screenshot_rate: "Evidence rate", consecutive_losses: "Loss streak", net_pnl: "Net P&L", weekly_reviews: "Reviewed weeks", profit_factor: "Profit factor" } as Record<string, string>)[metric] ?? metric; }
export function formatGoalValue(metric: string, value: number) { if (["daily_loss", "weekly_drawdown", "net_pnl"].includes(metric)) return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 }).format(value); if (["win_rate", "quality_setup", "screenshot_rate"].includes(metric)) return `${value.toFixed(1)}%`; if (["avg_rr", "profit_factor"].includes(metric)) return value.toFixed(2); return metric === "avg_patience" ? `${value.toFixed(1)} / 5` : String(Math.round(value)); }

export function assessTraderGoal(goal: TraderGoal, trades: GoalTrade[], plans: GoalPlan[] = [], now = new Date()) {
  const start = periodStart(goal.period, now); const today = dayKey(now); const rows = trades.filter(row => { const key = dayKey(row.tradeDate); return row.result !== "OPEN" && key >= start && key <= today; }).sort((a, b) => new Date(a.tradeDate).getTime() - new Date(b.tradeDate).getTime()); const relevantPlans = plans.filter(plan => { const key = dayKey(plan.planDate); return key >= start && key <= today && plan.overallRating != null; });
  const wins = rows.filter(row => row.result === "WIN"); const losses = rows.filter(row => row.result === "LOSS"); const netPnl = rows.reduce((sum, row) => sum + toNumber(row.pnl), 0); const grossProfit = wins.reduce((sum, row) => sum + Math.max(0, toNumber(row.pnl)), 0); const grossLoss = Math.abs(rows.reduce((sum, row) => sum + Math.min(0, toNumber(row.pnl)), 0));
  const values: Record<string, number> = { trade_count: rows.length, daily_loss: Math.max(0, -netPnl), revenge_trades: rows.filter(row => (row.mistake ?? "").toLowerCase().includes("revenge")).length, avg_patience: rows.length ? rows.reduce((sum, row) => sum + toNumber(row.patienceScore), 0) / rows.length : 0, win_rate: rows.length ? wins.length / rows.length * 100 : 0, avg_rr: rows.length ? rows.reduce((sum, row) => sum + (toNumber(row.risk) > 0 ? toNumber(row.reward) / toNumber(row.risk) : 0), 0) / rows.length : 0, weekly_drawdown: maxDrawdown(rows), quality_setup: rows.length ? rows.filter(row => row.setupQuality === "A" || row.setupQuality === "A+").length / rows.length * 100 : 0, screenshot_rate: rows.length ? rows.filter(row => Boolean(row.hasScreenshot)).length / rows.length * 100 : 0, consecutive_losses: currentLossStreak(rows), net_pnl: netPnl, weekly_reviews: relevantPlans.length, profit_factor: grossLoss ? grossProfit / grossLoss : grossProfit ? 99 : 0 };
  const value = values[goal.metric] ?? 0; const target = toNumber(goal.target); const hasActivity = rows.length > 0 || relevantPlans.length > 0; const usage = target > 0 ? Math.min(100, Math.abs(value) / target * 100) : 0; let status: TraderGoalStatus = "PENDING";
  if (hasActivity && goal.comparison === "GTE") status = value >= target ? "MET" : "IN_PROGRESS";
  if (hasActivity && goal.comparison === "LTE") status = value > target ? "BREACHED" : value >= target * 0.8 ? "AT_RISK" : "SAFE";
  const remaining = goal.comparison === "GTE" ? Math.max(0, target - value) : Math.max(0, target - value); const periodLabel = goal.period === "DAILY" ? "today (PKT)" : goal.period === "WEEKLY" ? "this week (PKT)" : "this month (PKT)";
  return { goal, value, target, rows: rows.length, hasActivity, status, percentage: usage, remaining, periodLabel, category: goalCategory(goal.metric), metricLabel: goalMetricLabel(goal.metric), current: formatGoalValue(goal.metric, value), targetLabel: formatGoalValue(goal.metric, target), remainingLabel: formatGoalValue(goal.metric, remaining) };
}
