import React, { useEffect, useMemo, useState } from "react";
import { Activity, Check, ChevronDown, Copy, Download, Landmark, Link2, Plus, Radio, RefreshCcw, Trash2, WifiOff } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { formatMoney, formatRr, toNumber } from "@/lib/gold";
import { toast } from "sonner";

const EA_DOWNLOAD = "/manus-storage/GoldJournal_EA_bf8ddfe3.mq5";
const pkt = (value?: string | Date | null) => value ? new Date(value).toLocaleString("en-PK", { timeZone: "Asia/Karachi", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "—";
const moneyOrDash = (value: string | number | null | undefined) => value == null ? "—" : formatMoney(value);
function connectionState(lastPing?: string | Date | null) { if (!lastPing) return { label: "Never connected", tone: "neutral" }; const elapsed = Date.now() - new Date(lastPing).getTime(); return elapsed <= 10_000 ? { label: "Connected", tone: "live" } : elapsed <= 60_000 ? { label: "Idle", tone: "idle" } : { label: "Offline", tone: "offline" }; }
function CopyValue({ value, label }: { value: string; label: string }) { const copy = async () => { try { await navigator.clipboard.writeText(value); toast.success(`${label} copied.`); } catch { toast.error("Copy is unavailable in this browser."); } }; return <button type="button" className="mt5-copy" onClick={() => void copy()} aria-label={`Copy ${label}`} title={`Copy ${label}`}><Copy size={14} /></button>; }
function Metric({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`mt5-account-metric ${tone}`}><span>{label}</span><strong className="data-text">{value}</strong><small>{detail}</small></article>; }

export function Mt5LiveView({ account }: any) {
  const accountInput = useMemo(() => account?.id ? ({ accountId: account.id }) : undefined, [account?.id]);
  const [historyPage, setHistoryPage] = useState(1); const [addOpen, setAddOpen] = useState(false); const [label, setLabel] = useState(""); const [oneTimeKey, setOneTimeKey] = useState(""); const [guideOpen, setGuideOpen] = useState(true);
  useEffect(() => setHistoryPage(1), [account?.id]);
  const historyInput = useMemo(() => account?.id ? ({ accountId: account.id, page: historyPage, pageSize: 20 }) : undefined, [account?.id, historyPage]);
  const workspace = trpc.mt5.workspace.useQuery(accountInput!, { enabled: Boolean(accountInput), refetchInterval: 2_500, refetchOnWindowFocus: true });
  const history = trpc.mt5.history.useQuery(historyInput!, { enabled: Boolean(historyInput), refetchInterval: 5_000, refetchOnWindowFocus: true });
  const createConnection = trpc.mt5.createConnection.useMutation(); const setActive = trpc.mt5.setConnectionActive.useMutation(); const deleteConnection = trpc.mt5.deleteConnection.useMutation(); const utils = trpc.useUtils();
  const connections = workspace.data?.connections ?? []; const activeConnection = connections.find((connection: any) => connection.active); const openPositions = workspace.data?.openPositions ?? []; const positions = history.data?.positions ?? []; const serverUrl = typeof window === "undefined" ? "/api/mt5" : `${window.location.origin}/api/mt5`;
  const refresh = () => { void utils.mt5.workspace.invalidate(); void utils.mt5.history.invalidate(); };
  const saveConnection = async () => { if (!account?.id || !label.trim()) return; try { const created = await createConnection.mutateAsync({ accountId: account.id, label: label.trim() }); setOneTimeKey(created.apiKey); setAddOpen(false); setLabel(""); toast.success("MT5 connection created. Copy the one-time API key into the EA now."); refresh(); } catch (error: any) { toast.error(error.message || "Could not create MT5 connection."); } };
  const historyStatus = !activeConnection ? "Create a connection to begin sync." : activeConnection.lastHistoryStatus === "FAILED" ? `History batch failed: ${activeConnection.lastHistoryMessage || "Check the EA log and connection."}` : activeConnection.lastHistorySync ? `${history.data?.total ?? activeConnection.historySyncedCount} closed positions synced · ${pkt(activeConnection.lastHistorySync)} PKT` : "Waiting for MT5 history.";
  return <section className="mt5-live-view">
    <header className="section-heading mt5-heading"><div><span className="eyebrow">DIRECT MT5 SYNC</span><h2>MT5 Live</h2><p>Only the selected account’s balance, positions, closes, and connection are shown here.</p></div><Button onClick={() => setAddOpen(true)} disabled={Boolean(connections.length)}><Plus size={16} /> Add connection</Button></header>
    <section className="mt5-account-panel panel"><div className="mt5-section-head"><div><span className="eyebrow">{account?.name || "ACTIVE ACCOUNT"}</span><h3>MT5 account snapshot</h3></div><Button variant="outline" size="sm" onClick={() => { void workspace.refetch(); void history.refetch(); }}><RefreshCcw size={14} /> Refresh</Button></div>{activeConnection?.balance == null ? <div className="mt5-empty compact"><Landmark size={24} /><h3>Waiting for MT5 account metrics</h3><p>Attach the EA to this terminal. Balance, equity, free margin, and floating P&amp;L appear after the next summary event.</p></div> : <><div className="mt5-account-grid"><Metric label="Balance" value={moneyOrDash(activeConnection.balance)} detail={activeConnection.currency || "MT5 currency"} tone="gold" /><Metric label="Equity" value={moneyOrDash(activeConnection.equity)} detail="Balance + floating P&L" /><Metric label="Floating P&L" value={moneyOrDash(activeConnection.floatingPnl)} detail="Open position result" tone={toNumber(activeConnection.floatingPnl) >= 0 ? "profit" : "loss"} /><Metric label="Free margin" value={moneyOrDash(activeConnection.freeMargin)} detail={`Margin ${moneyOrDash(activeConnection.margin)}`} /></div><p className="mt5-account-detail">Login {activeConnection.mt5Login || "—"} · {activeConnection.brokerServer || "MT5 terminal"} · Last terminal contact {pkt(activeConnection.lastPing)} PKT</p></>}</section>
    <section className="mt5-connection-section"><div className="mt5-section-head"><div><span className="eyebrow">{account?.name || "ACTIVE ACCOUNT"}</span><h3>MT5 connection</h3></div><span className="mt5-sync-indicator"><Activity size={14} /> {workspace.isFetching ? "Refreshing…" : "Live refresh every 2.5s"}</span></div>{connections.length ? <div className="mt5-connection-grid">{connections.map((connection: any) => { const state = connectionState(connection.lastPing); return <article className="mt5-connection-card" key={connection.id}><header><div><span className={`mt5-status ${state.tone}`}><i /> {state.label}</span><h4>{connection.label}</h4><small>{connection.accountName}</small></div><label className="mt5-switch"><input type="checkbox" checked={connection.active} onChange={event => void setActive.mutateAsync({ accountId: account.id, connectionId: connection.id, active: event.target.checked }).then(refresh).catch((error: any) => toast.error(error.message || "Connection could not be updated."))} /><span /></label></header><div className="mt5-secret-row"><span>API KEY</span><code>{connection.apiKeyMasked || "••••••••"}</code></div><div className="mt5-secret-row"><span>SERVER URL</span><code>{serverUrl}</code><CopyValue value={serverUrl} label="Server URL" /></div><footer><small>{connection.lastPing ? `Last contact ${pkt(connection.lastPing)} PKT` : "Waiting for the first EA ping."}</small><button type="button" className="text-danger" onClick={() => { if (!window.confirm(`Delete ${connection.label}? Historical MT5 records remain with this account.`)) return; void deleteConnection.mutateAsync({ accountId: account.id, connectionId: connection.id, confirmed: true }).then(() => { toast.success("MT5 connection deleted."); refresh(); }).catch((error: any) => toast.error(error.message || "Could not delete connection.")); }}><Trash2 size={14} /> Delete</button></footer></article>; })}</div> : <div className="mt5-empty"><Link2 size={28} /><h3>No MT5 connection yet</h3><p>Create one private connection for {account?.name || "this account"}, then copy its one-time key into the EA.</p><Button onClick={() => setAddOpen(true)}><Plus size={16} /> Add connection</Button></div>}</section>
    <section className={`mt5-guide panel ${guideOpen ? "open" : ""}`}><button type="button" className="mt5-guide-toggle" onClick={() => setGuideOpen(!guideOpen)}><div><span className="eyebrow">SETUP GUIDE · EA v1.13</span><h3>How to connect MT5 and backfill history</h3></div><ChevronDown size={18} /></button>{guideOpen && <ol><li><div><strong>Download and install the EA</strong><p>Replace any earlier Gold Journal EA build, then attach it to the correct terminal account.</p></div><a className="button-link" href={EA_DOWNLOAD} download="GoldJournal_EA.mq5"><Download size={15} /> Download EA v1.13</a></li><li><div><strong>Allow the server URL</strong><p>In MT5: Tools → Options → Expert Advisors. Enable WebRequests and add the address below.</p><div className="mt5-inline-copy"><code>{serverUrl}</code><CopyValue value={serverUrl} label="Server URL" /></div></div></li><li><div><strong>Use the matching API key</strong><p>Paste the one-time key for this exact Gold Journal account in the EA inputs. Keep BrokerUtcOffsetHours at 3 for broker UTC+3 timestamps.</p></div></li></ol>}</section>
    <section className="mt5-position-section"><div className="mt5-section-head"><div><span className="eyebrow">{account?.name || "ACTIVE ACCOUNT"}</span><h3>Open positions</h3></div><span className="mt5-live-dot"><Radio size={14} /> Live</span></div>{openPositions.length ? <div className="mt5-position-grid">{openPositions.map((position: any) => <article key={position.ticket} className={`mt5-position-card ${toNumber(position.floatingPnl) >= 0 ? "profit" : "loss"}`}><header><div><h4>{position.symbol}</h4><span className={`side-badge ${position.direction.toLowerCase()}`}>{position.direction}</span></div><strong className={`data-text ${toNumber(position.floatingPnl) >= 0 ? "positive" : "negative"}`}>{formatMoney(position.floatingPnl)}</strong></header><div className="mt5-metrics"><span>Risk <b>{formatMoney(position.riskUsd)}</b></span><span>Reward <b>{formatMoney(position.rewardUsd)}</b></span><span>R:R <b>{formatRr(position.riskUsd, position.rewardUsd)}</b></span></div><footer><span>{position.lots} lots · {pkt(position.openTime)} PKT</span></footer></article>)}</div> : <div className="mt5-empty compact"><WifiOff size={24} /><h3>No open positions in MT5</h3><p>Positions appear after this account’s active EA connection sends data.</p></div>}</section>
    <section className="mt5-closed-section panel"><div className="mt5-section-head"><div><span className="eyebrow">HISTORICAL CLOSED POSITIONS</span><h3>MT5 trade history</h3><p className="mt5-history-status">{historyStatus}</p></div><button type="button" className="icon-button" onClick={() => { void workspace.refetch(); void history.refetch(); }} aria-label="Refresh MT5 history"><RefreshCcw size={16} /></button></div>{positions.length ? <><div className="mt5-table-wrap"><table className="mt5-table"><thead><tr><th>Date</th><th>Symbol</th><th>Direction</th><th>Risk</th><th>Reward</th><th>R:R</th><th>P&amp;L</th><th>Result</th><th>Trade Log</th></tr></thead><tbody>{positions.map((position: any) => <tr key={position.ticket}><td>{pkt(position.closeTime)}</td><td>{position.symbol}</td><td><span className={`side-badge ${position.direction.toLowerCase()}`}>{position.direction}</span></td><td>{formatMoney(position.riskUsd)}</td><td>{formatMoney(position.rewardUsd)}</td><td>{formatRr(position.riskUsd, position.rewardUsd)}</td><td className={`data-text ${toNumber(position.realizedPnl) >= 0 ? "positive" : "negative"}`}>{formatMoney(position.realizedPnl)}</td><td>{position.result?.replace("_", " ")}</td><td><span className="mt5-journaled"><Check size={13} /> {position.journaled ? "Synced" : "Syncing"}</span></td></tr>)}</tbody></table></div>{(history.data?.pageCount ?? 1) > 1 && <div className="table-pagination"><span>Page {history.data?.page} of {history.data?.pageCount} · {history.data?.total} closed positions</span><div><Button variant="outline" size="sm" disabled={historyPage === 1 || history.isFetching} onClick={() => setHistoryPage(page => page - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={historyPage >= (history.data?.pageCount ?? 1) || history.isFetching} onClick={() => setHistoryPage(page => page + 1)}>Next</Button></div></div>}</> : <p className="mt5-no-closed">{history.isLoading ? "Loading MT5 history…" : "Historical MT5 closes appear here as the EA backfills them, then they are added automatically to Trade Log."}</p>}</section>
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add MT5 connection</DialogTitle><DialogDescription>Create one private connection for the selected Gold Journal account.</DialogDescription></DialogHeader><div className="mt5-add-form"><label>Connection label<Input value={label} onChange={event => setLabel(event.target.value)} placeholder="GFT 10K Account" /></label></div><div className="dialog-actions"><Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button><Button disabled={!label.trim() || createConnection.isPending} onClick={() => void saveConnection()}>{createConnection.isPending ? "Creating…" : "Create connection"}</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(oneTimeKey)} onOpenChange={open => { if (!open) setOneTimeKey(""); }}><DialogContent><DialogHeader><DialogTitle>Copy your MT5 API key now</DialogTitle><DialogDescription>This key is shown once. Store it in the matching EA input before closing this dialog.</DialogDescription></DialogHeader><div className="mt5-one-time-key"><code>{oneTimeKey}</code><CopyValue value={oneTimeKey} label="MT5 API key" /></div><div className="dialog-actions"><Button onClick={() => setOneTimeKey("")}>I copied the key</Button></div></DialogContent></Dialog>
  </section>;
}
