import React, { useMemo } from "react";
import { CheckCircle2, Clipboard, Download, ExternalLink, MonitorCog, PlayCircle, ShieldAlert, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import { downloadMt5Bridge } from "@/lib/mt5BridgeInstaller";

type Props = { bridgeUrl: string; targetName: string; targetReady: boolean; status: string; onTest: () => void; onImport: () => void; importing: boolean };

function Step({ number, title, children, state = "pending" }: { number: number; title: string; children: React.ReactNode; state?: "pending" | "ready" }) {
  return <article className={`mt5-guide-step ${state}`}><span className="mt5-step-number">{state === "ready" ? <CheckCircle2 size={15} /> : number}</span><div><h3>{title}</h3><div>{children}</div></div></article>;
}

export function Mt5SetupGuide({ bridgeUrl, targetName, targetReady, status, onTest, onImport, importing }: Props) {
  const cleanUrl = bridgeUrl.trim().replace(/\/$/, "") || "http://localhost:7842";
  const statusUrl = `${cleanUrl}/status`;
  const urlWarning = useMemo(() => { try { const parsed = new URL(cleanUrl); return parsed.hostname !== "localhost" && parsed.hostname !== "127.0.0.1" ? "This bridge is configured away from localhost. The browser must be able to reach that address and the bridge must allow this app’s origin with CORS." : ""; } catch { return "The bridge URL is invalid. Use a complete address such as http://127.0.0.1:7842."; } }, [cleanUrl]);
  const copy = async () => { try { await navigator.clipboard.writeText(statusUrl); } catch { /* Clipboard can be unavailable in embedded browsers. */ } };
  const connected = status.toLowerCase().includes("connected");

  return <section className="panel mt5-setup-guide">
    <div className="panel-title"><div><span>MT5 CONNECTOR</span><h3>Connect the right MT5 account in five steps</h3></div><MonitorCog size={18} /></div>
    <div className="mt5-guide-intro"><ShieldAlert size={18} /><p><strong>Important:</strong> Gold Journal cannot open MetaTrader 5 directly. The local connector must run on the <strong>same Windows PC and browser</strong> as the MT5 terminal. It never asks for your MT5 password.</p></div>
    {urlWarning && <div className="mt5-guide-warning"><ShieldAlert size={16} /><span>{urlWarning}</span></div>}
    <div className="mt5-guide-steps">
      <Step number={1} title="Choose the source MT5 terminal"><p>If you have multiple MT5 accounts, open the one you want to import and note its <strong>terminal64.exe</strong> location. A connector can target that exact terminal. Do not assume the bridge will choose the correct account automatically.</p></Step>
      <Step number={2} title="Download and start the connector"><p>Install the MetaTrader5 package once, then start the connector in a separate PowerShell or VS Code terminal. <strong>Keep that terminal window open</strong> while testing and importing. Seeing <code>KeyboardInterrupt</code> after pressing Ctrl+C only means you stopped the connector; it is not a bridge failure.</p><div className="mt5-connector-actions"><Button onClick={downloadMt5Bridge}><Download size={15} /> Download MT5 connector</Button><code>pip install MetaTrader5</code><code>python gold_journal_mt5_bridge.py --terminal "C:\Path\To\terminal64.exe" --port 7842</code></div><p>For another MT5 terminal, start a second copy with its own terminal path and port, for example <code>--port 7843</code>, then set this page’s Bridge URL to <code>http://127.0.0.1:7843</code> before importing that account.</p><div className="mt5-endpoint"><code>GET {statusUrl}</code><button type="button" onClick={() => void copy()} aria-label="Copy bridge status URL"><Clipboard size={14} /></button><a href={statusUrl} target="_blank" rel="noreferrer" aria-label="Open bridge status endpoint"><ExternalLink size={14} /></a></div><small>The connector must return HTTP 200 with JSON such as <code>{'{"ok":true,"account":{"login":"..."}}'}</code>.</small></Step>
      <Step number={3} title="Test and confirm the MT5 login" state={connected ? "ready" : "pending"}><p>Test the connection. A successful response names the connected MT5 login and server. Confirm it is the same source account you opened in step 1 before importing. If it is not, stop the script with Ctrl+C, restart it with the correct <code>--terminal</code> path and port, then test again.</p><Button variant="outline" onClick={onTest}><Wifi size={15} /> Test bridge connection</Button></Step>
      <Step number={4} title="Map to the correct Gold Journal account" state={targetReady ? "ready" : "pending"}><p>{targetReady ? <>MT5 history will import into <strong>{targetName}</strong>. This destination is separate from the source MT5 login checked in step 3; verify both before the first import.</> : "Choose an existing Gold Journal account or create a dedicated account below. The import button stays disabled until this mapping is explicit."}</p></Step>
      <Step number={5} title="Import closed history into Gold Journal"><p>Set the history window, then import. The connector returns each closed MT5 deal to this browser, which saves it to the selected cloud journal. MT5 ticket markers prevent the same deal from being saved twice.</p><Button disabled={importing} onClick={onImport}><PlayCircle size={16} /> {importing ? "Importing…" : "Go to live import controls"}</Button></Step>
    </div>
    <section className="mt5-troubleshooting"><div><span className="section-label">IF THE CONNECTOR DOES NOT WORK</span><h3>Read the matching recovery path</h3></div><div className="mt5-trouble-grid"><article><strong>“KeyboardInterrupt”</strong><p>This is a normal shutdown caused by Ctrl+C. Start the script again and leave the terminal running while you test or import.</p></article><article><strong>Wrong MT5 account appears</strong><p>Stop the connector, reopen the correct MT5 terminal, then restart with that terminal’s full <code>--terminal</code> path. Use a different <code>--port</code> for each simultaneously running account.</p></article><article><strong>“Failed to fetch” or connection refused</strong><p>The connector is not running at this URL. Check the terminal window, port, local firewall, and Bridge URL.</p></article><article><strong>MetaTrader5 package or terminal error</strong><p>Run <code>pip install MetaTrader5</code>, then open and sign in to the Windows MT5 terminal before starting the connector.</p></article><article><strong>Import says 0 added</strong><p>Confirm the selected MT5 login has closed deals in the chosen day range. Increase the window, then retry. Existing ticket markers are correctly skipped.</p></article><article><strong>Trades land in the wrong journal</strong><p>Stop before importing, choose the correct Gold Journal destination below, then retry. Source terminal and destination journal are deliberately confirmed separately.</p></article></div></section>
    <footer className="mt5-guide-footer"><strong>Current bridge response:</strong><span>{status}</span></footer>
  </section>;
}
