import React, { useMemo, useState } from "react";
import { CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney, toNumber } from "@/lib/gold";
import { weeklyPnl } from "@/lib/performanceSummary";

export function PnlCalendarWithWeeks({ trades }: { trades: any[] }) {
  const [month, setMonth] = useState(new Date()); const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0);
  const cells = useMemo(() => [...Array.from({ length: first.getDay() }, () => null), ...Array.from({ length: last.getDate() }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))], [first, last, month]);
  const weeks = useMemo(() => Array.from({ length: Math.ceil(cells.length / 7) }, (_, index) => cells.slice(index * 7, index * 7 + 7)), [cells]);
  return <><section className="section-heading"><div><span className="eyebrow">P&L RHYTHM</span><h2>PnL Calendar</h2><p>Review daily execution, then check each week-end total before carrying risk into the next session.</p></div><div className="month-controls"><Button variant="outline" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>Prev</Button><span>{month.toLocaleString("en-US", { month: "long", year: "numeric" })}</span><Button variant="outline" onClick={() => setMonth(new Date())}>This month</Button><Button variant="outline" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>Next</Button></div></section><section className="panel calendar-panel weekly-calendar"><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => <span key={day}>{day}</span>)}</div>{weeks.map((week, weekIndex) => { const present = week.filter(Boolean) as Date[]; const start = present[0] || new Date(month.getFullYear(), month.getMonth(), 1); const end = present[present.length - 1] || start; const pnl = weeklyPnl(trades, new Date(start.getFullYear(), start.getMonth(), start.getDate(), 0, 0, 0), new Date(end.getFullYear(), end.getMonth(), end.getDate(), 23, 59, 59)); const count = trades.filter(trade => { const value = new Date(trade.tradeDate); return value >= start && value <= end; }).length; return <div className="calendar-week-block" key={`${month.toISOString()}-${weekIndex}`}><div className="pnl-calendar">{week.map((day, index) => { if (!day) return <div className="calendar-blank" key={index} />; const rows = trades.filter(trade => new Date(trade.tradeDate).toDateString() === day.toDateString()); const daily = rows.reduce((sum, trade) => sum + toNumber(trade.pnl), 0); return <div className={`day-cell ${rows.length ? daily >= 0 ? "gain" : "loss" : ""}`} key={day.toISOString()}><span>{day.getDate()}</span>{rows.length ? <><strong className="data-text">{formatMoney(daily)}</strong><small>{rows.length} trade{rows.length > 1 ? "s" : ""}</small></> : <small>No trades</small>}</div>; })}</div><div className={`week-total ${pnl >= 0 ? "positive" : "negative"}`}><CalendarDays size={15} /><span>Week ending {end.toLocaleDateString("en-GB", { day: "2-digit", month: "short" })} · {count} trade{count === 1 ? "" : "s"}</span><strong className="data-text">{formatMoney(pnl)}</strong></div></div>; })}</section></>;
}
